### ISSUE TITLE
Juego de la fruta

### ISSUE THREAD

**Issue by Mornheo** [samgreenb/TripleJam#1]
yes

**Comment by rlebron22** [comment]
el sirculo crack

**Comment by rlebron22** [comment]
![image](https://user-images.githubusercontent.com/67839607/86519805-c0326780-be3e-11ea-8701-51a2306ea7a3.png)

**Comment by rlebron22** [comment]
![image](https://user-images.githubusercontent.com/67839607/86519954-12c05380-be40-11ea-8f77-f998a81ea7da.png)
